### ISSUE TITLE
Message Read and Write through code

### ISSUE THREAD

**Issue by pratik-pk** [tomer8007/whatsapp-web-incognito#10]
Can we read the message sent to me through the given code and and store it  in some variable.
and send back the message through code published by you

**Comment by tomer8007** [comment]
Do you ask if we can MITM messages? The answer is yes.
I can publish an example code if you'd like.

**Comment by pratik-pk** [comment]
yes, that will be very helpful for our project.
Are you having any youtube channel where you explain your code

**Comment by tomer8007** [comment]
You can now use the [manipulateSentNode](https://github.com/tomer8007/whatsapp-web-incognito/blob/master/core/Main.js#L180) function to inspect and change outgoing nodes and messages. just after the `var message = messageTypes.WebMessageInfo.parse(nodeReader.children(child));` line.

Beyond that, take a look at the flow in `wsHook.before` and in `wsHook.before`. This is the core.

If you want to see for yourself what is getting received and sent normally, you can type `WADebugMode = true` in the javascript console.

I hope this helps.
(and I don't have any youtube channel)

**Comment by pratik-pk** [comment]
thanks for your fast response.
but now when I download the latest release and load it into the chrome extension it's throwing error.
that you can't able to use it please write back to developer

**Comment by pratik-pk** [comment]
console.error("WhatsAppInvisible: can't decrypt packet due to exception:");

**Comment by tomer8007** [comment]
Are you using the latest version from the Chrome Web Store?
I don't think you need to load it unpacked.

**Comment by tomer8007** [comment]
I also updated the latest relase. Please try that.

**Comment by mylene-balicuas-thesis** [comment]
Hi! How could I decrypt messages sent for MultiDevice in NodeHandler.manipulateSentMessageNode as it is done in NodeHandler.isReceivedNodeAllowed?

**Comment by tomer8007** [comment]
Decryption of incoming multi-device messages with Signal is not something that I've implemented yet. Maybe in the future.

**Comment by mylene-balicuas-thesis** [comment]
Ok, thanks
