### ISSUE TITLE
whatsapp don't open

### ISSUE THREAD

**Issue by 9Gabr** [tomer8007/whatsapp-web-incognito#104]
My whatsapp ins't opening, I tested without using the extension and works fine (in vivaldi and chrome).

(Just blurred my contacts numbers) 

![WhatsApp Image 2022-11-10 at 00 22 31](https://user-images.githubusercontent.com/92824047/200993276-3dbbe932-65a9-45ba-abaf-0a4d85068bbc.jpeg)

**Comment by 9Gabr** [comment]
Thanks for your work Tomer, it's fixed for me. 😁

And I know it's ins't a proper way, 
but I see this extension: https://chrome.google.com/webstore/detail/turn-off-whatsapp-read-re/efchedgcidabcebiogkefabechhkonja?hl=en-GB

I think they have copied your code.

**Comment by tomer8007** [comment]
@9Gabr Yes, this is definitely a copy. Reported abuse.
