### ISSUE TITLE
cant open view once picture

### ISSUE THREAD

**Issue by Shizu-ka** [tomer8007/whatsapp-web-incognito#106]
Someone send view-once picture, even tho the picture hasn't been deleted, it looks like it has been deleted and i can't open it.
[imageExample](https://ibb.co/KLbFpvF)

**Comment by 9Gabr** [comment]
It's not a bug from the extension, whatsapp changed the view once thing to only show in mobile:

> Starting 1 November 2022, WhatsApp web and desktop users won’t be able to send or receive view once media. This change is to support the rollout of screenshot blocking for view once messages. From this date, if you’d like to send or receive view once media, you’ll need to do so from your mobile device.

[Whatsapp Help Center](https://faq.whatsapp.com/578442220724722/?helpref=uf_share)

**Comment by w4po** [comment]
@tomer8007 
Is it possible to open/show it anyway? can we find a hack around it?

![Screenshot_20230201_074129](https://user-images.githubusercontent.com/6666887/215962770-ac523224-ca2d-4d4d-b626-c64d4f2925b6.png)

**Comment by tomer8007** [comment]
@w4po Maybe it's possible if the web version actually received the message (which I believe this is the case). If you're interested you can open a separate issue.
