### ISSUE TITLE
Getting online status / Simulating chat click

### ISSUE THREAD

**Issue by ShadyThGod** [tomer8007/whatsapp-web-incognito#11]
I have a couple of questions which if you could answer, would be amazing.

1. I know of a way to check if the user is online by getting the value of `props.chat.presence.isOnline`, but the correct value of that can only be gotten once the chat is opened. I want to get the correct value of the presence when all the chats are loaded, without having to open them. Is this possible?

2. Is there a way to programmatically open a chat? By this, I mean is it possible to simulate clicking one of the chats to open that certain chat? I tried using the `element.click()` method, but that doesn't do anything.

Thanks, 
Aman.

**Comment by ShadyThGod** [comment]
By the way, I'm sorry if this is off-topic. I think you might be able to help me out, which is why I've asked you.

**Comment by tomer8007** [comment]
Yes.
1. Two ways, if your JID is something like "PHONE_NUMBER@g.us":
a. `WhatsAppAPI_1.Chat.get(jid).presence.isOnline`
b.  `getChatByJID(jid).presence.isOnline`
2. This can be a matter of extracting the module that exports the function `openChat` and calling it. I'm not sure how to do that at the moment, but I can see that it's getting called when you open a chat. Maybe I'll get back to that later.

**Comment by ShadyThGod** [comment]
> 1. Two ways, if your JID is something like PHONE_NUMBER@g.us:
>    a. `WhatsAppAPI_1.Chat.get(jid).presence.isOnline`
>    b.  `getChatByJID(jid).presence.isOnline`

I tried doing this, but it keeps showing false even when it is actually false.

**Comment by tomer8007** [comment]
> I tried doing this, but it keeps showing false even when it is actually false.

Do you mean that when you get a chat object via `getChatByJID(jid)` or by any other method, that would not reflect the real online status unless the chat is opened? 

I think this could be because you need to subscribe to presence updates somehow.  

Did you try typing `WADebugMode = true`? When you click on a chat, you see:

![image](https://user-images.githubusercontent.com/11458759/72409574-d48a8700-376e-11ea-9853-babcf5795221.png)

**Comment by ShadyThGod** [comment]
> Do you mean that when you get a chat object via `getChatByJID(jid)` or by any other method, that would not reflect the real online status unless the chat is opened?

Yes, that is what I mean.

**Comment by ShadyThGod** [comment]
Is there a way to use your API in an Electron app? I'm trying to implement a feature in my electron app where it checks if the chats are online or not and shows a marker if someone is online.

**Comment by tomer8007** [comment]
If I were you I would spend time trying to extract the modules I need to open a chat, subscribe to presence updates of users, etc.
This is what I've done with the API that sends read receipts. You can see the code that finds some of the `webpack` modules [here](https://github.com/tomer8007/whatsapp-web-incognito/blob/master/core/Main.js#L770).

This should work straight-away in javascript, assuming the javascript in WhatsApp's Electron app (or whatever it is) is similar in its form to the WhatsApp Web version.

**Comment by tomer8007** [comment]
In fact, it looks like the [sulla ](https://github.com/danielcardeenas/sulla)project has already extracted the OpenChat API in this way [over here](https://github.com/danielcardeenas/sulla/blob/master/src/lib/wapi.js#L25).

**Comment by ShadyThGod** [comment]
@tomer8007 Thank you very much! I got the chats to open with the `OpenChat` API.
And with the presence thing, I need to find a way to make the chats not `stale`. It doesn't get the correct `presence.isOnline` value if `presence.stale` is true.

**Comment by tomer8007** [comment]
Turns out that's easier:

`chat.presence.subscribe()`

will turn your `char.presence.stale` to false and reveal the real `chat.presence.isOnline`.

**Comment by ShadyThGod** [comment]
Thank you so much! It works now! I'll close this issue now.
