### ISSUE TITLE
New whatsapp update just broke the extension.

### ISSUE THREAD

**Issue by 9Gabr** [tomer8007/whatsapp-web-incognito#110]
![image](https://user-images.githubusercontent.com/92824047/212135130-dbd74304-7a8e-46ff-aa1b-cb3fdd6718a7.png)

Version: 2.2301.6

**Comment by tomer8007** [comment]
@Ashesh3 Is there a change that you're using an older version `2.2247.7` < `2.2301.6`?

**Comment by Ashesh3** [comment]
You are right! That's my bad, it works great after i cleared cache and hard refreshed, on `Version 2.2301.6` now! Thanks for this amazing project.
