### ISSUE TITLE
Messy menu when WA Web Plus is installed

### ISSUE THREAD

**Issue by eduardokabello** [tomer8007/whatsapp-web-incognito#112]
Why is this happening, any idea?

![Captura de tela 2023-01-15 114352](https://user-images.githubusercontent.com/90769476/215934105-7c21f525-3e5f-4d23-9f0a-d6d79efc03d2.png)

**Comment by Shizu-ka** [comment]
i guess its browser problem, mine is fine
try update the browser

**Comment by tomer8007** [comment]
@eduardokabello Is your screen/window resolution standard?

**Comment by eduardokabello** [comment]
> @eduardokabello Is your screen/window resolution standard?

My monitor resolution is 2560 x 1440

**Comment by 9Gabr** [comment]
> its because happen when u install another plugin privacy for whatsapp.. try uninstall other plugin, it will be fixed.

I can confirm, when you use _WAincognito_ with _WA Web Plus_ the menu looks messy like this.

**Comment by tomer8007** [comment]
Thank you, this is fixed now.

**Comment by eduardokabello** [comment]
@tomer8007 Nice! Now I'm just waiting new updated version. Thank you!

**Comment by cheemeng** [comment]
Sorry to reopen an old issue but I think the menu thingy is back.

Adding a 
```css
  flex-wrap: wrap;
```
to `.incognito-options-view-container` seems to fix it for me.
