### ISSUE TITLE
Not Working in New Version of WhatsApp Web

### ISSUE THREAD

**Issue by hardasmith2** [tomer8007/whatsapp-web-incognito#113]
Hello, i tried several times to reinstall and install again the plugin. When someone send me a text, its still read able with blue tick..
Its happen after i logout from last session.. Before i logout from web, its working normally.. Any fix for this? Thankyou so much.

**Comment by chandrapw** [comment]
same here, web version 2.2305.7

**Comment by w4po** [comment]
Same here, The extension icon is shown on the webpage but it doesn't prevent seen status (not working).

**Comment by tomer8007** [comment]
That's a bit unusual - a protocol change. The new `contact` packet looks weird, so I don't know what they were thinking..

**Comment by valga** [comment]
@tomer8007 They upgraded dictionaries version from 2 to 3, so almost all tokens are different now.

**Comment by tomer8007** [comment]
@valga Thank you, I'll try to work on a better solution.
