### ISSUE TITLE
The disable read reception ( blue ticks) doesnt work

### ISSUE THREAD

**Issue by ritastar** [tomer8007/whatsapp-web-incognito#114]
Hello there! con la actulización de  fecha 02/02/2022 no funciona la no confirmación de lectura de un mensaje ( blue ticks) por lo tanto la otra persona ya sabe cuando leo y escucho los mensajes, por favor si lo pueden arreglar? Gracias!

**Comment by w4po** [comment]
Prevent read reception (for messages) is working (after the latest update 571464d).
But for voice notes, it's not working.

**Comment by ritastar** [comment]
Efectivamente ya no se confirma la lectura con el doble ticket azul pero los audios se marcan como escuchados, ojalá lo puedan solucionar pronto, de todas maneras mil gracias por el trabajo que hacen. ¡Son geniales!

**Comment by tomer8007** [comment]
Should work for voice now.

**Comment by w4po** [comment]
> Should work for voice now.

Yes, It works for me, Thank you very much ❤️👍
