### ISSUE TITLE
Official Firefox support now that Manifest v3 is possible

### ISSUE THREAD

**Issue by simplebunsen** [tomer8007/whatsapp-web-incognito#117]
I've read that since Firefox 109 it supports Mv3, so it should be possible to officially release the extension for the Firefox store, right? Kind regards

**Comment by Neutrino-Tech** [comment]
https://github.com/tomer8007/whatsapp-web-incognito/issues/103

**Comment by simplebunsen** [comment]
Thanks for mentioning that Neutrino. Do the devs want to officially upload it to the firefox store then? :)

**Comment by tomer8007** [comment]
I don't want to upload it to the Firefox store right now (I will need to maintain it and there aren't as many users as in Chrome), but you can always load it manually from GitHub

**Comment by simplebunsen** [comment]
Thanks for clarifying, that is sad to hear :( Is it then possible to load the github extension without dealing with all of the special voodoo concerning firefox developer uploading and using some beta firefox as I read in other issues?
