### ISSUE TITLE
Auto send read confirmations when you send a message

### ISSUE THREAD

**Issue by izzues** [tomer8007/whatsapp-web-incognito#12]
Pretty much what the title says, as a toggleable option. Additionally, if you reply to a previous message, it could be configured to send confirmations only up to that message and leave newer ones "unread".

Thanks a lot for your work!

**Comment by tomer8007** [comment]
This should now work in version [1.5.7](https://github.com/tomer8007/whatsapp-web-incognito/commit/21e895b0030a97bfac82f195f6d85169d40e6c99).

**Comment by izzues** [comment]
Awesome, thank you! :)
