### ISSUE TITLE
Deleted messages not being restore, in last version 2.0.2

### ISSUE THREAD

**Issue by diegoweb** [tomer8007/whatsapp-web-incognito#121]
Hey!

In this last version whenever someone deletes a message, WA-Incognito is not restoring the message.
Instead it replaces the message "This message was deleted"
![image](https://user-images.githubusercontent.com/12632119/227319487-2281a261-fc8d-4c29-a17d-69bcd73cbb89.png)

With this when you change to chat with another person and comes back to this one that had the message deleted:
![image](https://user-images.githubusercontent.com/12632119/227319601-6cb318c2-e2d1-4a65-922d-38275ab34e01.png)

And the option to restore is enabled in the extension
![image](https://user-images.githubusercontent.com/12632119/227319680-e4c2ff65-f456-4ce6-b9aa-0bfd72d54874.png)

**Comment by tomer8007** [comment]
Last time I checked this worked for me. Any javascript errors maybe?

**Comment by diegoweb** [comment]
> Last time I checked this worked for me. Any javascript errors maybe?

![image](https://user-images.githubusercontent.com/12632119/227322101-9f44ede5-6865-4ecf-807e-c8019ba48d20.png)

This is all I could see when I ask someone to delete the message.

**Comment by tomer8007** [comment]
Looks like one of the more annoying bugs. Did this feature worked for you before 2.0.2? Can you try to re-login?

**Comment by tomer8007** [comment]
Yes, the errors here are normal. I don't know why you lost your history, but oh well.
Maybe in the future I'll work on a feature to sync more history.

**Comment by diegoweb** [comment]
> Yes, the errors here are normal. I don't know why you lost your history, but oh well. Maybe in the future I'll work on a feature to sync more history.

Actually, nevermind.
It's still syncing the history.

😝 

Thanks!

**Comment by diegoweb** [comment]
@tomer8007 I just noticed that if a group admin deletes someone else's message, this extension doesn't restore the deleted message. Would you be able to implement that?

**Comment by tomer8007** [comment]
@diegoweb I didn't know this is even a feature in WhatsApp. Yes, I'd like to implement that, that please open a separate issue.
