### ISSUE TITLE
Implement revoke messages for messages deleted by Group Admins

### ISSUE THREAD

**Issue by diegoweb** [tomer8007/whatsapp-web-incognito#122]
Hey!

So far as I could tell the Revoke Message feature in this extension only work for private conversation, so only between 2 people.

WhatsApp has recently added a feature that allow Group Admins to delete message from participants in a group and Wa-Incognito doesn't restore the deleted message in this case.

Could you please implement this feature in the next version of this extension?

Thanks!

**Comment by tomer8007** [comment]
The Restore messages feature does work for groups, though, just not for messages deleted by admins I guess.

**Comment by diegoweb** [comment]
> The Restore messages feature does work for groups, though, just not for messages deleted by admins I guess.

Yup, you're right. It does work for groups if the user who sent the message is the one deleting it. But it doesn't work by messages deleted by admin.

**Comment by tomer8007** [comment]
I believe this should work now in version 2.0.3. Please confirm.

**Comment by diegoweb** [comment]
> I believe this should work now in version 2.0.3. Please confirm.

I disabled the chrome downloaded extension and installed this one via developer (unpacked extension) and refreshed the web whatsapp page.

I tried:
Sending a message as User A
Deleting the message as User B (admin)
Trying to see the message as user C (running the extension)

It did not work.
Do I have to re-login?

**Comment by tomer8007** [comment]
No, it probably doesn't work yet :-(
It did work for me when the admin deleted _your_ message from the group.
Can you share javascript errors?

**Comment by diegoweb** [comment]
> No, it probably doesn't work yet :-(
> It did work for me when the admin deleted _your_ message from the group.
> Can you share javascript errors?

Well, it worked with the extension updated from Chrome Store.
But for some reason sometimes the browser freezes when you visit a group with the restored message, and you get this javascript error:


ui.js:642 Uncaught TypeError: Cannot set properties of undefined (setting 'textContent')
    at HTMLDocument.<anonymous> (ui.js:642:34)

**Comment by tomer8007** [comment]
I can see what cases the javascript error, it's a stupid mistake.
But do you at least see the deleted message?

**Comment by tomer8007** [comment]
For how long does it freeze?

**Comment by diegoweb** [comment]
> For how long does it freeze?

Over 10 seconds

**Comment by tomer8007** [comment]
Can you try to comment out lines 139-150 here,
https://github.com/tomer8007/whatsapp-web-incognito/blob/de895a42006b067799ea113b39a7af2d22867620/core/utils.js#L139
so that it will use the fallback method?
I have a feeling it's related to the freeze, but am not sure.

**Comment by tomer8007** [comment]
Actually maybe it's a bad idea. If you can find a javascript warning it will be far better. I just don't have a 3rd user to test with right now,

**Comment by diegoweb** [comment]
There's no javascript warning besides that one.
And actually I just tested multiple times here, and no Javascript error goes to the console when the browser freezes.

**Comment by tomer8007** [comment]
> When I scroll down to see the recovered message, the browser freezes.

It makes sense because this is when the restore function gets called. I just can't think of anything that might block in this flow.
Are you sure the browser freezes only in this case where an Admin deletes a message, and in no other cases?

**Comment by tomer8007** [comment]
OK, well, I guess I'll need a 3rd device to test. If you really want to you can try to do single-stepping from `restoreDeletedMessageIfNeeded` to find the hanging function in the meantime :-(.

**Comment by diegoweb** [comment]
I will see if I can try that and if I found something useful.
But one thing that I noticied is that I can't PIN any chat anymore (after that re-login in the previous github issue). Is that supposed to happen?

![image](https://user-images.githubusercontent.com/12632119/227678921-d9212d03-e20c-4d90-8688-336814d51be8.png)

**Comment by tomer8007** [comment]
I think really that the pinning of chats is something that WhatsApp did not yet implement for the web.
It has nothing to do with the extension.

**Comment by diegoweb** [comment]
I had to disable the extension and refresh the page. So all my pinned chats were back on the top.
Then I enabled the extension again and refreshed the page once more.
Now everything is working as expected 😛 

I think the extension is messing with something, if you previously had pinned chat already.
But that was an easy fix, so don't worry about it.

**Comment by tomer8007** [comment]
@diegoweb Yes, this sounds like exactly what happened to me.

**Comment by tomer8007** [comment]
Closing because it seems messages deleted by admins are restored correctly.
