### ISSUE TITLE
Feature Request: enable viewing view once media

### ISSUE THREAD

**Issue by sshehab1** [tomer8007/whatsapp-web-incognito#128]

**Comment by shifoc** [comment]
that's a nice feature

**Comment by IsaacHatton** [comment]
I think it's possible, if so this seems like Meta really didn't bother to engineer this properly to only send to the primary mobile device.
![image](https://github.com/tomer8007/whatsapp-web-incognito/assets/74068072/9a44b370-7f59-48de-89dd-9ca8cc4a5bca)
As using the URL I can download a file.enc in the browser, my theory is that if someone can find how the key included can unlock this file, it is possible to do this, my research came up with this but I have no idea how to format the key in a way that this will unlock it https://github.com/ddz/whatsapp-media-decrypt

Also, consider that this will completely break view once privacy, and therefore doing this could attract the attention of Meta and also could create some ethical issues as users are told that their content can't be shared, although I suppose at this point the extension already allows delete prevention so this isn't that different.

**Comment by tomer8007** [comment]
@sshehab1 @IsaacHatton  I'm pretty sure there's also just a javascript function that can decrypt `enc` files from WhatsApp web. We can use that.
Please restore the issue comments so that it will be easier to implement in the future.

**Comment by IsaacHatton** [comment]
Just written some code that will console.log the data URI for the viewonce message, will make a pull request when I have worked out how to integrate with the UI.
https://github.com/IsaacHatton/whatsapp-web-incognito/commit/7694f23e975da7af36802192d5686b68aab8a647
