### ISSUE TITLE
"Forwarded" label not sent with messages

### ISSUE THREAD

**Issue by izzues** [tomer8007/whatsapp-web-incognito#13]
I'm not sure if this is by design, but it was unexpected. It's not really that important, but I have one (admittedly very unusual) use for this feature.

Is it possible to show this label? Does it require sending read confirmations or presence updates?

Thanks in advance!

**Comment by tomer8007** [comment]
Do you see this label when you forward a message to someone else, when you get a forwarded message, or never?

**Comment by izzues** [comment]
Oops, I wasn't clear at all, sorry. I can see the label both when I forward a message to someone else and when I receive a forwarded message, but other people don't see labels on messages I forward do them.

**Comment by tomer8007** [comment]
Thank you a lot for reporting this concrete bug, it was reproducable and I believe that its cause was also the cause of other bugs.

This is now fixed in version [1.5.8](https://github.com/tomer8007/whatsapp-web-incognito/commit/610e48adb6d94f425f347841d836fb4bdf04bcdd).

**Comment by izzues** [comment]
Really glad I could help! Thank you!
