### ISSUE TITLE
WhatsApp Web gets stuck on "Loading your chats" when linking your device

### ISSUE THREAD

**Issue by mapokapo** [tomer8007/whatsapp-web-incognito#134]
After you scan the QR code on the WhatsApp Web website, the "Loading your chats" text takes unusually long (around 5-10 minutes). After that, you get taken back to the QR code page with an error above saying "Your device could not link due to a sync issue. Please relink your device."

Trying again, the same thing happens.

Here are screenshots of the problem:
![image](https://github.com/tomer8007/whatsapp-web-incognito/assets/47316453/74d331af-be26-4a9e-82e0-c476a87edb24)

![image](https://github.com/tomer8007/whatsapp-web-incognito/assets/47316453/d03ddc90-c449-4878-ad5f-129de15f2734)

Notes:
- Disabling WhatsApp Web Incognito fixes this issue, so you can link your device normally.
- WhatsApp Web Incognito works normally only if you enable it after you have linked your device.

**Comment by tomer8007** [comment]
Thanks for the report. I think I could get rid of the "maximum call stack" error in version 1.0.8 and scanning the QR seems to work fine for me now. Please let me know if this changes anything.
