### ISSUE TITLE
Not syncing messages properly

### ISSUE THREAD

**Issue by para8ox-deb** [tomer8007/whatsapp-web-incognito#149]
This extension works super cool, but most of the time it has sync problem. In my phone I even message someone but that message is not shown in the web whatsapp, even after refreshing it many times, the messages are not syncd properly. 
Kindly fix the issue of syncing, without extension syncing works fine.

**Comment by tomer8007** [comment]
Hello,
1) Does the message restore feature work for you?
2) I suspected the sync problems are because of the last update where I fixed the message restore feature. Did you try disabling it to see if it fixes the sync problems?

**Comment by para8ox-deb** [comment]
1. Yes the message restore feature is working fine for me.
2. Exactly, just now I turned off the restore message feature and then refreshed the page, I got all latest messages. The problem lies when restore feature is on.

Kindly fix this thing so that we can use both restore message and sync together properly.

**Comment by tomer8007** [comment]
@para8ox-deb Does the problem still occur in version 2.1.2?

**Comment by wagnerlcc** [comment]
Sim, ocorre, mas nao sei do que se trata restauracao de mensagens... onde eu vejo isso?

**Comment by wagnerlcc** [comment]
![image](https://github.com/tomer8007/whatsapp-web-incognito/assets/155816036/b33e76f3-35aa-4c93-aae6-9a6a8f9ce8af)

SERIA O restored messages deleted?

**Comment by justanotheranonymoususer** [comment]
I'm seeing a similar issue, often I have to refresh the page to see new messages in the browser

**Comment by tomer8007** [comment]
@justanotheranonymoususer @wagnerlcc @para8ox-deb In version 2.1.3 I changed the message restore feature so that instead of dropping the whole stanza, it screws up the internal message. In this way the WhatsApp client sends an acknowledgment for the message, which could make the syncing of messages more correct.

Please let me know if the new version fixes the problem for you or not.

**Comment by justanotheranonymoususer** [comment]
I didn't encounter the problem lately, so maybe fixed, I'll keep monitoring

**Comment by wagnerlcc** [comment]
hi, morning

Today I try to was listening to some audio messages received and the play
button does not work properly.
I uncheck deleted restore messages but the problem does not resolve.
Do you know about this issue?






Wagner Carvalho
CEO | Diretoria
WLCC Consultoria e Gestão
***@***.***





Em qua., 17 de jan. de 2024 às 12:53, justanotheranonymoususer <
***@***.***> escreveu:

**Comment by tomer8007** [comment]
@wagnerlcc This is unrelated here, please open a separate issue for it.
@justanotheranonymoususer @wagnerlcc @para8ox-deb I'll close this issue because I didn't get reports it still happens.
