### ISSUE TITLE
Pinned, archived channels not synced

### ISSUE THREAD

**Issue by justanotheranonymoususer** [tomer8007/whatsapp-web-incognito#152]
Took me a long while to notice that whatsapp-web-incognito causes this.

1. I pinned a channel, it didn't appear on web for weeks, until now I disabled the extension
2. I archived a channel, and it continued spamming on web, even after refresh, until I disabled wa-web

Now that I know this, workaround is simple as pin/archive isn't common, but it can be surprising

**Comment by tomer8007** [comment]
I was able to see that when this is happening this is written to the log:

![image](https://github.com/tomer8007/whatsapp-web-incognito/assets/11458759/507854fd-118f-415f-9966-2bb805df645c)

![image](https://github.com/tomer8007/whatsapp-web-incognito/assets/11458759/a7ab0007-2906-4a06-9019-dcb4e0493da0)

Will try to investigate.

**Comment by tomer8007** [comment]
@justanotheranonymoususer Can you please check if version 2.1.3 fixes the problem? I made some changes that could be related to the problem.

**Comment by justanotheranonymoususer** [comment]
Seems to be fixed now, thanks.

**Comment by justanotheranonymoususer** [comment]
😀

Paul Jackson reacted via Gmail
<https://www.google.com/gmail/about/?utm_source=gmail-in-product&utm_medium=et&utm_campaign=emojireactionemail#app>
