### ISSUE TITLE
"Don't send "Last Seen" and "Typing" updates" checkbox changes don't update immediately

### ISSUE THREAD

**Issue by IsaacHatton** [tomer8007/whatsapp-web-incognito#155]
When you change the "Don't send "Last Seen" and "Typing" updates" checkbox, the setting is only respected when the page reloads.

Should the text be modified to say it requires a reload, should the page reload or is there a way to make it work without a reload?

**Comment by tomer8007** [comment]
I am aware that this is indeed the case when you un-tick this option. When you tick it, it should affect right away. The relevant enforcing variable is actually changed immediately but it doesn't do the effect when un-ticking. I think it's basically because the client stops to send presence updates until you reload or something like that.

I don't think this is a big enough problem to be described in the GUI. Maybe we can just how an alert when un-ticking saying you should refresh.

**Comment by IsaacHatton** [comment]
Maybe it's my environment, but loading the page in with the box unticked, then ticking it seems to not block the online reciepts? 
Mobile devices were locked with the screen turned off.
Left side is my main with the current Chrome Webstore version
Right side is my test with no extension

This behaviour was very annoyingly intermittent, it seems to only work sometimes, and I can't figure out what I am doing different (might be a timing thing).

![image](https://github.com/tomer8007/whatsapp-web-incognito/assets/74068072/9065f553-7fab-4f4e-bb5a-65d1bad38d18)

As a sidenote, a second mobile device linked as a secondary device to an account shows up as a laptop under the "Show device of messages" feature, but I presume that's not something that's worth creating a change over?

**Comment by IsaacHatton** [comment]
https://blog.whatsapp.com/one-whatsapp-account-now-across-multiple-phones

I only use it on my test account, where the primary is Dual Messenger on my android and companion is an old iPhone and a second Edge profile on my laptop.

On my primary, I have Whatsapp for Windows and my main Edge profile as companions.

**Comment by tomer8007** [comment]
> https://blog.whatsapp.com/one-whatsapp-account-now-across-multiple-phones

I see. The update that added the device feature was released in March 2023, because this announcement. Also see my edit regarding the "Last seen" feature.

**Comment by IsaacHatton** [comment]
RE the edited message, that makes sense and would explain the testing behaviour I saw, do you know what function can be called to make the person be marked as "not-available"?

**Comment by IsaacHatton** [comment]
This is functional, is this what we are looking for?
![image](https://github.com/tomer8007/whatsapp-web-incognito/assets/74068072/cc891b74-c601-44c8-912c-76e00d99d329)
From my testing, Name can be left blank.

I can't seem to find it in WhatsAppAPI but maybe I'm looking in the wrong place.

**Comment by tomer8007** [comment]
Fixed in pull request #156 .
