### ISSUE TITLE
Extension breaks after WhatsApp version 2.3000

### ISSUE THREAD

**Issue by tjodiro** [tomer8007/whatsapp-web-incognito#159]
This version is not working and is not loading any update?

**Comment by tomer8007** [comment]
Thanks for opening an issue. 
What's the WhatsApp Web version you're using? The extension works for me in  2.2411.2.

**Comment by inalam** [comment]
@tjodiro do you use WA Web Plus by Elbruz Technologies? try disable it, mine works after that

**Comment by tjodiro** [comment]
nothing seems to work

**Comment by GHMFL0369** [comment]
the whats app version is Version 2.3000.1012148573

**Comment by GHMFL0369** [comment]
![Screenshot 2024-03-19 071234](https://github.com/tomer8007/whatsapp-web-incognito/assets/132157390/5c28c0fd-7b40-4562-90fd-fc520f8db0f1)

**Comment by tomer8007** [comment]
@GHMFL0369 Looks like the message is self-explanatory.

**Comment by GHMFL0369** [comment]
![Screenshot 2024-03-19 195652](https://github.com/tomer8007/whatsapp-web-incognito/assets/132157390/70192ed6-c67a-4744-a0fc-7b37f71d2719)

**Comment by inalam** [comment]
@GHMFL0369 have you try enabling the beta? using non beta makes my version in 2.3000 and beta could go to 2.2412.1

**Comment by tomer8007** [comment]
@inalam Does anybody have a tip on how to enter 2.3000? I've having some trouble moving to this version from 2.2412.1.

**Comment by tomonetml** [comment]
@tomer8007 probably enabling betas in settings, help

**Comment by tomer8007** [comment]
@tomonetml  Already tried that, and also trying from another OS, browser, and re-logging in didn't help moving out of 2.2412.1.

**Comment by inalam** [comment]
> @inalam Does anybody have a tip on how to enter 2.3000? I'm having some trouble moving to this version from 2.2412.1.

i just uncheck the beta
![image](https://github.com/tomer8007/whatsapp-web-incognito/assets/34022787/4bdd159d-2ca1-498d-9ed3-2c33ceec92a6)

version with beta
![image](https://github.com/tomer8007/whatsapp-web-incognito/assets/34022787/e947160b-2e81-481e-8be4-aba72d915b83)


and always empty cache and hard refresh between change
![image](https://github.com/tomer8007/whatsapp-web-incognito/assets/34022787/3cef7943-fd21-4baf-85d7-56ca096a9881)

it's weird the fact that beta has lower version than official(?)

**Comment by tomer8007** [comment]
> and always empty cache and hard refresh between change

Yep I always do this

> it's weird the fact that beta has lower version than official(?)

Absolutely, also noted that

For me both options still leave me in 2.2412.1. My phone also runs version 2.24.X.
I think that 2.3000 is in some kind of limited edition, perhaps only for some users.

**Comment by IsaacHatton** [comment]
My main whatsapp account is broken in stable, I tried it in beta also.
With WAdebugMode enabled:
![image](https://github.com/tomer8007/whatsapp-web-incognito/assets/74068072/432e2000-562d-4b5b-bc78-9956a24c4b61)

I presume the first error is due to some UI based change, but I don't know about the second.

**Comment by IsaacHatton** [comment]
For the UI change, here's what the new DOM looks like for where the buttons are
![image](https://github.com/tomer8007/whatsapp-web-incognito/assets/74068072/56777aec-d5b9-4fe6-8c76-3c90f2adca62)

**Comment by tomer8007** [comment]
Can anyone share thoughts about how to enter the new version? Do you know others that have 2.2411.2 and can tell the difference?

**Comment by IsaacHatton** [comment]
I have found that if you are in stable 2.24... and you switch to beta and reload it upgraded me most times.

I by using various browser profiles have managed to get it to pick me either versions, I think it's based on an identifer in the browser rather than the account as to whether you get selected for the A/B test.

**Comment by tomer8007** [comment]
> and you switch to beta and reload it
You do this using the browser or the phone?

**Comment by tomer8007** [comment]
> I'm having some trouble moving to this version from 2.2412.1.

![image](https://github.com/tomer8007/whatsapp-web-incognito/assets/11458759/ba6ed430-1dc5-4cfb-b779-2b1213ef0fe4)
Adding `Cookie: wa_beta_version=production/1710826334/2.2412.1; wa_build=c;` to the headers did the trick.

**Comment by IsaacHatton** [comment]
> > I by using various browser profiles have managed to get it to pick me either versions
> 
> What OS and browser did you use?

Win 11: both Edge and Chrome

**Comment by tomer8007** [comment]
@IsaacHatton So how did you make it pick 2.2412.1 vs 2.3000?

**Comment by IsaacHatton** [comment]
> @IsaacHatton So how did you make it pick 2.2412.1 vs 2.3000?

Just keeping logging in and out in different browsers, I did not have a methodology really.

**Comment by m4heshd** [comment]
@tomer8007 It's a staged rollout. You might need to wait a couple of days.

Also, always use the browser's **Guest** profile/mode to log in. Even incognito can sometimes affect how the headers are sent back to their endpoint to decide if you're a viable candidate for the update.

**Comment by tomer8007** [comment]
> You might need to wait a couple of days.

As I said I managed to make WhatsApp update me to the new version by adding `wa_build=c;` to the cookies. Looks like this is really new, even newer than the newest version available for beta testers in Android and iOS. It appears they're now using React Native for the web.

**Comment by IsaacHatton** [comment]
> > You might need to wait a couple of days.
> 
> As I said I managed to make WhatsApp update me to the new version by adding `wa_build=c;` to the cookies. Looks like this is really new, even newer than the newest version available for beta testers in Android and iOS. It appears they're now using React Native for the web.
> 
> **UPDATE**: @IsaacHatton I have released version [2.1.5](https://github.com/tomer8007/whatsapp-web-incognito/releases/tag/v2.1.5) of the extension which adds support for WhatsApp Web 2.3000.

Thanks for releasing that, it works great for me, has it updated on the chrome webstore yet or does Google require manual approval for updates (I only have experience with the Edge extension store)?

**Comment by tomer8007** [comment]
> has it updated on the chrome webstore yet

Yes, version 2.1.5 is live on the store now.

**Comment by IsaacHatton** [comment]
Thanks.

Just as a thought, if you could pick which version you got served, as a long term strategy could there be a system implemented wherein if the extension fails to load and it detects there's a newer version, it can add the header to downgrade to the old one?

**Comment by tomer8007** [comment]
Currently version 2.1.5 is backward-compatible with both 2.3000 and 2.24.X (tested on both).
In case WhatsApp releases a new version that breaks stuff, you normally see the popup that @GHMFL0369 posted earlier in this thread.

**Comment by tomer8007** [comment]
As for downgrading WhatsApp versions, we need to be sure what `wa_build` actually means.

**Comment by IsaacHatton** [comment]
Oh ok, that makes sense. I misread this:
>  Adding `Cookie: wa_beta_version=production/1710826334/2.2412.1; wa_build=c;` to the headers did the trick.

as when you put wa_beta_version you could select the version from there.

I presume any kind of system to automatically send error logs when that popup appears wouldn't be allowed under app store rules, as the Privacy Policy says so https://github.com/tomer8007/whatsapp-web-incognito/wiki/Chrome-Extension-Privacy-Policy ?

**Comment by tomer8007** [comment]
> as when you put wa_beta_version you could select the version from there.

Yeah, I'm still not certain about exactly what is the purpose of this cookie.

> any kind of system to automatically send error logs

Yes, I don't like this privacy-wise, it requires me to setup and maintain a back-end system, and I think most of the time users will already complain and I will also note that myself.

**Comment by tomer8007** [comment]
Closing this because it's fixed now
