### ISSUE TITLE
Group messages

### ISSUE THREAD

**Issue by Gahamelas** [tomer8007/whatsapp-web-incognito#17]
Would this work for group messages also? I notice that read receipt in Whatsapp can be hidden in personal messages, but when it comes to groups, the sender can have access to whom has seen their message/media.

**Comment by tomer8007** [comment]
The short answer is Yes.

**Comment by Gahamelas** [comment]
Short? I don't understand. Any extra steps I have to take to make sure?

**Comment by tomer8007** [comment]
When you read a group message when read receipts blocking is turned on, the receipt will not be setnt to the group. You can verify this by creating a test group and see for yourself.

**Comment by Gahamelas** [comment]
I use the chrome extension and it's always open. So the receipts should be blocked.

**Comment by tomer8007** [comment]
Yes. As long as you have the "Dom't send read confirmations" checkbox checked.

**Comment by Gahamelas** [comment]
Yes, but its like that set up by default when you add the extension. Right?

**Comment by tomer8007** [comment]
I think so..
