### ISSUE TITLE
Possible memory leak?

### ISSUE THREAD

**Issue by pablo-gbr** [tomer8007/whatsapp-web-incognito#171]
Hi, I've been using the extension since quite long time, and recently when I enter a conversation that has like +500 unread messages or multiple conversations, the entire tab starts to lag really bad, causing my ram usage to go pretty high.

I think it has something to do with all the `console.log` the extension does, maybe enclose them in a debug flag?

**Comment by tomer8007** [comment]
I can't debug this without having 500+ unread messages. Can you point the relevant debug prints?

**Comment by pablo-gbr** [comment]
Sorry about the late reply, but I tested on a laptop with win 11 with the same amount of messages, and it works like a charm. But on my pc with win 10 it starts to lag real bad, I don't know if it's caused by other extensions or not, and it started to happen on chats with 1 unread message.

So I don't know the cause yet, I'll update if I find anything.

**Comment by pablo-gbr** [comment]
I found out that it was a config issue with my browser, I excluded whatsapp web from the list and now it works. Closing this
