### ISSUE TITLE
Feature Request: Can you implement edit log feature.

### ISSUE THREAD

**Issue by doesDeveloper** [tomer8007/whatsapp-web-incognito#178]
Explanation: This feature will allow to see unedited version and final edited version of messages received.

Thanks

**Comment by tomer8007** [comment]
There is already an issue for this in #126.

**Comment by doesDeveloper** [comment]
@tomer8007 but that issue has been closed without any followup pr?

**Comment by tomer8007** [comment]
You can re-open it, but I'm not going to work on this soon. If you want, you can try to use the code there to see edited messages. It works, just without GUI.
