### ISSUE TITLE
Camapaña de Whatsapp para que no se empleen aplicaciones de terceros

### ISSUE THREAD

**Issue by ritastar** [tomer8007/whatsapp-web-incognito#181]
Estaba pensado que quizas el problema por el cual no puedo vincular la extension web con mi dispositivo celular ( escanear el QR)  se debe que a partir de la versión oficial 2.24.12.15 en adelante  no deja escanear el QR con dichas app de terceros ( web-incognito)  porque la cuenta oficial de whatsaap porque consideran que pueden poner en riesgo mi dispositivo. Sabes algo de esto Tomer?  Ojala se pueda solucionar

**Comment by tomer8007** [comment]
Hello, I don't think that WhatsApp is denying scanning the QR code becuase it thinks the extension can put you at risk or something like that. Anyway I'm closing this issue because you've already opened one in the same subject.
