### ISSUE TITLE
Extension does not load in actual version

### ISSUE THREAD

**Issue by Barradel** [tomer8007/whatsapp-web-incognito#22]
Error: extension does not load after using WhatsApp Web in another Chrome window or PC

Steps to reproduce: 

1 - Login in WhatsApp Web in a Chrome window n. 1
2 - Login in WhatsApp Web (same number) in a Chrome window n. 2 (will log off the WhatsApp in window n. 1) 
3 - Re-login in WhatsApp Web (same number) again. The WhatsApp Web will open correctly, but without load this extension.

I checked the code, but I cannot help with my actual knowledge.

By the way, I am a user and a big fan of this work. Congratulation.

**Comment by tomer8007** [comment]
Thanks, this is now fixed in version [1.6.2](https://github.com/tomer8007/whatsapp-web-incognito/commit/be0ae7c4b086e21dd9137046b6796fd40aeb131e)
