### ISSUE TITLE
Mark as read without confirmation

### ISSUE THREAD

**Issue by justanotheranonymoususer** [tomer8007/whatsapp-web-incognito#24]
Great addon!

I'd like to be able to easily mark as read. Currently there's a big modal warning, asking whether I'm really really sure, every time I click on "mark as read".
Pleas add an option to not show it. Thanks.

**Comment by tomer8007** [comment]
Thanks, this is now done in 40154669104599f88ef4ed6684fd9f34f874b144.

**Comment by justanotheranonymoususer** [comment]
Wow, that was super fast, thanks!
