### ISSUE TITLE
Bug: can't mark as read if was explicitly marked unread (without count)

### ISSUE THREAD

**Issue by justanotheranonymoususer** [tomer8007/whatsapp-web-incognito#25]
See screenshot. The button does nothing.

![image](https://user-images.githubusercontent.com/5781692/94082963-bcddc500-fe0a-11ea-9ce5-1fb354d81285.png)

**Comment by tomer8007** [comment]
Nice bug. I'll fix this next version

**Comment by tomer8007** [comment]
Fixed in 8f2f76a393d3a8b202fe1d7c9e0519063d34fc35.
