### ISSUE TITLE
voice messages aren't blocked anymore

### ISSUE THREAD

**Issue by schneivo77** [tomer8007/whatsapp-web-incognito#27]
Hi,
in the current version voice messages aren't blocked anymore. The "marked as read" button still appears above them but the icon turns to blue when I play them.

**Comment by tomer8007** [comment]
But text messages are blocked correctly?

**Comment by schneivo77** [comment]
Yes.

**Comment by tomer8007** [comment]
Regarding Edit 3, This sounds like the normal behavior because the extension shows "Read receipets were blokced" only when the device actually tries to send out a receipt, not immediately when you open a chat.

I'm not sure what is happening from your other edits, I'll try to test it myself.

**Comment by tomer8007** [comment]
Okay, Nice catch.
I added blocking of playing recipts in 0087a403d399bf976ffb8e8d28e4ad78efbc4cd7.

**Comment by schneivo77** [comment]
Nice! Thank you! Looking forward to the release! :)

**Comment by schneivo77** [comment]
Hi, with v1.6.4 blocking the voice messages is working pretty good! :)
Unfortunately a little bit too good...  I can't send out a read receipt now even if I want to do so by clicking the "mark as read" button. 😅
Is this possible to fix?

**Comment by tomer8007** [comment]
Oh,
I'll try to see if there's a quick fix for it later, shouldn't be hard. At least for now you can just temporarily disable read receipts blocking, right?

**Comment by schneivo77** [comment]
Temporarily disabling is at least a good workaround! :)

**Comment by tomer8007** [comment]
So read receipts for voice messages are blocked correctly. Problems with sending read receipts for them could be another issue :-(
