### ISSUE TITLE
Cannot manually mark as read/unread in submenu

### ISSUE THREAD

**Issue by justanotheranonymoususer** [tomer8007/whatsapp-web-incognito#28]
![image](https://user-images.githubusercontent.com/5781692/95689363-e6735a80-0c18-11eb-96ff-260f0f74dac7.png)

**Comment by tomer8007** [comment]
Yes, this is because the extension blocks every `read` packet, which also includes marking as unread.
Do you want this feature?

**Comment by justanotheranonymoususer** [comment]
Well, I use it sometimes. Not a big deal, I can grab my phone for it, but if those user actions can be whitelisted that can be nice. I'd guess that unlike reading a regular message, these actions don't send information to the server and just mark in the local db. But perhaps it doesn't matter for the web view which should notify the phone anyway.

**Comment by tomer8007** [comment]
Yeah, this action sends out a packet to notify the phone and it's implemented as sending a read receipt with a negative count of messages depending on how many unread messages you already had.

Should be preety easy to add, I'll just have to make sure this won't break other things.

**Comment by tomer8007** [comment]
@justanotheranonymoususer With multi-device this functionality is implemented using `syncd` so this bug does not happen anymore.
