### ISSUE TITLE
Firefox support?

### ISSUE THREAD

**Issue by andreksu** [tomer8007/whatsapp-web-incognito#34]
Hey everyone! I would like to request Firefox support! If it already does work then how can I install? I can't seem to find the extension on the Firefox extension store or anywhere. Thanks!

**Comment by tomer8007** [comment]
Firefox should already be supported in d272cea0f6d108afe52b9767401bd01a230cae80, and you should be able to install it with Firefox Developer Edition.

**Comment by alefranzoni** [comment]
Yes, Firefox is fully supported. I'm using on it and I don't have any problems at all! 😁
