### ISSUE TITLE
Whatsapp incognito stopped working

### ISSUE THREAD

**Issue by wepa2000** [tomer8007/whatsapp-web-incognito#35]
It simply won't load
![Screen Shot 2021-01-03 at 17 33 05](https://user-images.githubusercontent.com/76923843/103491581-ade3b700-4dea-11eb-8eba-67f352af5e0b.png)

**Comment by tomer8007** [comment]
Hmm, it does appear to load for me, what version of WhatsApp are you using?

**Comment by tomer8007** [comment]
This is most likely related to #37
