### ISSUE TITLE
contact

### ISSUE THREAD

**Issue by YOEL311** [tomer8007/whatsapp-web-incognito#36]
Hi, Tomer, I wanted to talk to you
I'd be happy If you contact me
yoel301@gmail.com

**Comment by tomer8007** [comment]
Hi, you can find contact details in the Chrome Web Store. Also next time you can use the [Q&A page](https://github.com/tomer8007/whatsapp-web-incognito/discussions/categories/q-a) for such questions.

**Comment by YOEL311** [comment]
I'm sorry
I did not think of this possibility
I sent you an email

**Comment by sakliteam** [comment]
i want mail send
