### ISSUE TITLE
 Maximum call stack size exceeds

### ISSUE THREAD

**Issue by elbeshenrique** [tomer8007/whatsapp-web-incognito#37]
When loaded, the console log this exception:
![image](https://user-images.githubusercontent.com/22816845/103889362-0bb32000-50c5-11eb-8f4e-9f12965cae96.png)

> binary_reader.js:28 Uncaught (in promise) RangeError: Maximum call stack size exceeded
>     at n (binary_reader.js:28)
>     at BinaryWriter.toBuffer (binary_writer.js:63)
>     at Object.WACrypto.packNodeForSending (crypto.js:144)
>     at interception.js:98
> Promise.then (async)
> (anonymous) @ interception.js:85
> K @ app.6be31a9914b3f8e528be.js:1
> p @ app.6be31a9914b3f8e528be.js:1
> wsHook.after @ interception.js:76
> (anonymous) @ VM270:65

**Apparently the only collateral effect noted is the lack of loading the contacts names (only recent ones).**

The exception occurs in the file 'binary_reader.js' line 28 at this point:
![image](https://user-images.githubusercontent.com/22816845/103889141-b119c400-50c4-11eb-90bc-913e8710c754.png)

**Comment by tomer8007** [comment]
Thanks for the debugging info. I can't reproduce this, but I temporarily removed the reproduction of received weboskcet nodes in 2c749f55a3c3c41efd870daa7418da7b35c6c028, which should avoid the exception.
