### ISSUE TITLE
Anyone Explain How Can i Install This Addon Firefox Stable

### ISSUE THREAD

**Issue by cakircan-cakir** [tomer8007/whatsapp-web-incognito#38]
I can only install the plugin from the debug menu. When I load it normally, it says the plugin is corrupt. When I load it from the debug menu and restart firefox, the plug-in is deleted. How can I install it normally?

**Comment by izzues** [comment]
As far as I know, you can't permanently install temporary add-ons on Firefox Stable, only on Nightly or Developer Edition. However, I'm getting the same error even in Firefox Nightly. I tried [this](https://www.reddit.com/r/firefox/comments/blqffs/how_to_permanently_add_temporary_addon/) but still get the same error.

([This](https://support.mozilla.org/en-US/questions/1183622) is the error message: "[add-on] could not be installed because Nightly cannot modify the needed file")

**Comment by cakircan-cakir** [comment]
The developer needs to publish this plugin in the store so we can install it easily

**Comment by alefranzoni** [comment]
@izzues @cakircan-cakir 
Yes you can, even if the developer doesn't publish the addon in the firefox store for everyone. It's really easy, follow these steps:

1. Download source and extension (from Releases)
2. Go to the developer page inside addons ff store
3. Upload a "new addon". In this case, select the option that the addon will be only for you (private, non-public, so it can be activated instantly)
4. You have to upload the extension and its code-source
5. That's all! You'll receive a mail confirmation with your addon in *.xpi and fully installable (permanent). You also can install it from your developer profile > addon page > versions.

Don't forget to check for new releases and update your extension to keep it update. It's all!

**Comment by w4po** [comment]
@alefranzoni 
It's not working anymore because Firefox doesn't support manifest v3:
Error: "Manifest V3 is currently not supported for upload"

Any workaround?

**Comment by alefranzoni** [comment]
@w4po Meanwhile, you can download and use the version **[1.7.8](https://github.com/tomer8007/whatsapp-web-incognito/releases/tag/v1.7.8)**, as it's the latest version supported by Firefox...

**Comment by lsfgrd** [comment]
> @w4po Meanwhile, you can download and use the version **[1.7.8](https://github.com/tomer8007/whatsapp-web-incognito/releases/tag/v1.7.8)**, as it's the latest version supported by Firefox. Check if that version meets your necessities.

Thanks for the guide! Any ideas why this can't be available on Firefox addon store like it is on Chrome?

**Comment by tomer8007** [comment]
We're waiting for Mozilla to add support for manifest v3:
https://discourse.mozilla.org/t/manifest-v3/94564/2

**Comment by gabrc52** [comment]
```diff
diff --git a/core/parsing/protobuf/WhisperTextProtocol.js b/core/parsing/protobuf/WhisperTextProtocol.js
index 4736f4a..904c801 100644
Binary files a/core/parsing/protobuf/WhisperTextProtocol.js and b/core/parsing/protobuf/WhisperTextProtocol.js differ
diff --git a/manifest.json b/manifest.json
index 5085da3..e0c7faf 100644
--- a/manifest.json
+++ b/manifest.json
@@ -1,5 +1,5 @@
 {
-  "manifest_version": 3,
+  "manifest_version": 2,
   "name": "WAIncognito",
   "short_name": "WAIncognito",
   "description": "Be invisible on WhatsApp™ Web by disabling read receipts and presence updates",
@@ -11,7 +11,8 @@
    },
    "background":
    {
-    "service_worker": "background.js"
+    "scripts": ["background.js"],
+    "persistent": true
    },
    "host_permissions": ["https://web.whatsapp.com/*"],
    "content_scripts": 
@@ -27,5 +28,6 @@
   	  "css": ["styles.css", "lib/css/drop-theme-basic.css"]
   	}
    ],
-	"web_accessible_resources": [{"resources": ["lib/*", "core/*", "images/*"], "matches": ["https://web.whatsapp.com/*"]} ]
-}
\ No newline at end of file
+   "web_accessible_resources": ["lib/*", "core/*", "images/*" ]
+}
+
```

I got it to run by making the following change in the manifest, and recompiling. But it doesn't actually work?

**Comment by Jhol86** [comment]
R
