### ISSUE TITLE
This plugin is already available in firefox?

### ISSUE THREAD

**Issue by pcampina** [tomer8007/whatsapp-web-incognito#41]
Hi I'm trying the WAIncognito in firefox "debug mode" the plugin works so great.

When plugin will be available on firefox?

**Comment by tomer8007** [comment]
Firefox is supported, you can see related discussions [here](https://github.com/tomer8007/whatsapp-web-incognito/issues?q=firefox).

**Comment by pcampina** [comment]
Okay but have one way to install directly from [Firefox Add-ons](https://addons.mozilla.org/en-US/firefox/search/?q=waincognito) ?

I can't understand how install

**Comment by tomer8007** [comment]
It's not in the store, you have to manually install it using the developer page as explained in #38.

**Comment by pcampina** [comment]
cool thank u
