### ISSUE TITLE
WhatsApp Web Bata tab crashes with "Out of Memory" error

### ISSUE THREAD

**Issue by shraga100** [tomer8007/whatsapp-web-incognito#44]
You can use the new version of WhatsApp Web by installing the bata app version [from here](https://www.apkmirror.com/apk/whatsapp-inc/).
After updating the app, you must join the bata version (via the "Linked Devices" option in the app) and link the device to WhatsApp Web.
While the 'whatsapp web incognito' extension is running, the WhatsApp Web tab in the browser crashes with "Out of Memory" error message and does not load.

![image](https://user-images.githubusercontent.com/26792728/126075354-93bc445e-a536-4a0d-a74f-93963488cdf8.png)

**Comment by tomer8007** [comment]
Thanks, It appears that before getting the "Out of Memory" error you are getting `Cannot read property 'encKey' of null` which I know can happen due to #43. Can you make that one go away at least?

**Comment by shraga100** [comment]
היי, תומר, 
אני שובר את השיניים עם האנגלית ופתאום אני שם לב שקוראים לך תומר... (אמנם בגיטהאב נהוג להתכתב באנגלית אבל אני רק משתמש פשוט שנהנה מהתוסף ולא מתכנת, אז סלחו לי...)
1. זה עבד אצלי עד עכשיו מצוין לפני שהחלפתי לגירסה החדשה של וואטסאפ ווב. רק בגירסה החדשה זה קורס.
2. מה זו האפשרות של "remember-me"? לא הצלחתי להבין.

**Comment by tomer8007** [comment]
![image](https://user-images.githubusercontent.com/11458759/126076238-d04e8a36-d1c9-4adb-973c-1f7c9d0b6bff.png)

**Comment by shraga100** [comment]
It still crashes even when the option is checked.

**Comment by tomer8007** [comment]
OK, I will try to look at that, thanks.
