### ISSUE TITLE
Enhancing accessibility

### ISSUE THREAD

**Issue by XP-Fan** [tomer8007/whatsapp-web-incognito#48]
Well, since as of https://github.com/tomer8007/whatsapp-web-incognito/issues/31 this seems to turn from incognito-only to a general WhatsApp Web enhancer, now I dare asking: Would you maybe be willing to enhance the accessibility of WhatsApp Web for blind people? Cause WhatsApp didn't care for years, so I guess they never will... What was basically required is that when a new message arrives within the currently focused chat, the screenreader should automatically read it, cause as things stand right now a blind person wouldn't even notice it. It would be also super awesome if typing notifications and presences would be automatically announced and if there was a keyboard shortcut to record/send a voice message. Unfocused chats are covered by desktop notifications afair. Maybe this resource might help you: https://a11y-guidelines.orange.com/en/web/components-examples/make-a-screen-reader-talk/

**Comment by tomer8007** [comment]
I'm not sure I want to go that far in the enhancements, #31 is just somethig that was highly requested and easy to implement. Are you aware of [WhatsappWebWithMoreAccessibility](https://github.com/juliano-lopes/accessibility-by-force/blob/master/src/js/WhatsappWebWithMoreAccessibility.js) though?

**Comment by XP-Fan** [comment]
Oh, no, I didn't know that. But what is it actually? Seems there is no readme, just a .js-file. What features does it have and/or what does it change? And most importantly: How could one even use that? I'm myself not a web developer, I'm an hardcore x86 asm only guy.

**Comment by tomer8007** [comment]
There's [this video](https://www.youtube.com/watch?v=UsKyes6-VjM) explaining. Not certain if it can read messages for you, though

**Comment by XP-Fan** [comment]
Well from the video it doesn't seem so and after listening that now I remember, actually a friend of mine who is also blind told me about that and he said it didn't automatically read new messages. It was some months ago though. But you're right, maybe it is more appropriate to ask that guy first then. I'l drop him an email real quick.
