### ISSUE TITLE
How can we disable typing.. in the icognito mode?

### ISSUE THREAD

**Issue by vishalv26** [tomer8007/whatsapp-web-incognito#5]

**Comment by tomer8007** [comment]
This should be pretty simple.
When you're typing, WhatsApp sends a message like this:

![image](https://user-images.githubusercontent.com/11458759/57869143-11cbfd00-780d-11e9-8dc8-ae673ba7f69e.png)

Just add another condition to [this line](https://github.com/tomer8007/whatsapp-web-incognito/blob/e3d3bf6acf252befe25ce1220c25598822f80a08/core/Main.js#L517), and you're good to good.

**Comment by vishalv26** [comment]
I think it should be part of the core as well. When hiding last seen/online status. It doesnt make any sense to show typing message.

**Comment by tomer8007** [comment]
[Done](https://github.com/tomer8007/whatsapp-web-incognito/commit/14eb3c5e66190c34157735850819d6c2f85a8558).
