### ISSUE TITLE
Isn't working anymore on actual WhatsWeb 

### ISSUE THREAD

**Issue by LcsPls** [tomer8007/whatsapp-web-incognito#53]
![image](https://user-images.githubusercontent.com/89872304/131565153-4f66bc1d-7a53-418a-8abd-98d252b871b4.png)

I use it in Firefox since always without problems, but around twelve o'clock in the afternoon it stopped working

**Comment by tomer8007** [comment]
I don't see this. Which version are you using? here's mine.

![image](https://user-images.githubusercontent.com/11458759/131709112-aef6f682-5fbb-4dac-9640-5446c823be06.png)

**Comment by LcsPls** [comment]
> 
> 
> I don't see this. Which version are you using? here's mine.
> 
> ![image](https://user-images.githubusercontent.com/11458759/131709112-aef6f682-5fbb-4dac-9640-5446c823be06.png)
> 
> Also any javascript errors please?

My version here:
![image](https://user-images.githubusercontent.com/89872304/131735193-28f36b2d-8356-47c2-94f5-f19b0e3c36c3.png)

And the any error that I get is that: 
![image](https://user-images.githubusercontent.com/89872304/131735227-0b853bdf-a4e1-410d-8953-19c742280f21.png)

:(

**Comment by tomer8007** [comment]
Now I am on 2.2134.10 but since don't get this message. Please open the console and share any javascript errors if you see them.

**Comment by LcsPls** [comment]
> 
> 
> Now I am on 2.2134.10 but since don't get this message. Please open the console and share any javascript errors if you see them.

I dont really know if is that, but here...

> TypeError: secretBundle is null
    getKeys moz-extension://7ebb7fce-04dd-4e93-855e-c41bf32aa865/core/crypto.js:174
    decryptWithWebCrypto moz-extension://7ebb7fce-04dd-4e93-855e-c41bf32aa865/core/crypto.js:13
    after moz-extension://7ebb7fce-04dd-4e93-855e-c41bf32aa865/core/interception.js:101
    j https://web.whatsapp.com/bootstrap_qr.428c60993dba5c1514a3.js:2
    v https://web.whatsapp.com/bootstrap_qr.428c60993dba5c1514a3.js:2
    after moz-extension://7ebb7fce-04dd-4e93-855e-c41bf32aa865/core/interception.js:86
    WebSocket https://web.whatsapp.com/:65
crypto.js:26:17

**Comment by tomer8007** [comment]
> TypeError: secretBundle is null

Not sure why your `secretBundle` is null, but it's not the first time that I see this, and I think that if you'll just log out and in again this might solve it. 

Anyway let's debug it. When you go to Application -> Local Storage/Session Storage, do you see a key named `WASecretBundle`?

**Comment by LcsPls** [comment]
> 
> 
> > TypeError: secretBundle is null
> 
> Not sure why your `secretBundle` is null, but it's not the first time that I see this, and I think that if you'll just log out and in again this might solve it.
> 
> Anyway let's debug it. When you go to Application -> Local Storage/Session Storage, do you see a key named `WASecretBundle`?

Hey, dude! Thank you very much.  I just logged out and logged in again and it now works again \o/

But, about local storage I didnt see nothing with "WaSecretBundle"

**Comment by tomer8007** [comment]
Well, I don't know what's causing this, but if it ever happens again to you, I'd like to figure it out.
