### ISSUE TITLE
Feature request: Sending images without loss of quality.

### ISSUE THREAD

**Issue by loopinspirou** [tomer8007/whatsapp-web-incognito#55]
In fact, WhatsApp has a function to control image compression, however, I've already tested it and realized that unfortunately it's not so good. The image still loses a lot of quality.

**Therefore, I propose the creation of a feature that allows sending images without loss of quality.**

Regarding the upload of videos, as far as I've analyzed, they don't suffer any type of compression when uploaded via WhatsApp Web, what can happen is that it won't be uploaded if it exceeds the 64 megabyte limit.

Greetings!

**Comment by tomer8007** [comment]
I think it's too far from the incognito nature of the extension
