### ISSUE TITLE
Not working on Chrome

### ISSUE THREAD

**Issue by AtomicNess123** [tomer8007/whatsapp-web-incognito#56]
I updated my Chrome web browser today, reinstalled the plugin but it won't work. When I click on my conversations, it shows a blank. Thanks!

**Comment by tomer8007** [comment]
This is because of a change WhatsApp made recently. It's working as of 2901a339f4af8df199e5973241e2e5861a1ee8af.

**Comment by tomer8007** [comment]
You can just install the latest version 1.7.6 from the [releases](https://github.com/tomer8007/whatsapp-web-incognito/releases/tag/v1.7.6).
