### ISSUE TITLE
'Interception is not working'

### ISSUE THREAD

**Issue by zeiphon** [tomer8007/whatsapp-web-incognito#6]
It seems that interception has stopped working (WA Incognito displays a prompt at load), perhaps in the latest whatsapp web version?

Currently on WhatsApp Web verison 0.3.4157

**Comment by tomer8007** [comment]
This is strange because I'm using WhatsApp Web version 0.3.4157 and I don't see this message.
Can you post what errors are printed in the javascript console?

Maybe it's complaining it can't find `encKey`?

**Comment by cardinal2019** [comment]
hello

![image](https://user-images.githubusercontent.com/53834246/62564052-9a7d9680-b85a-11e9-9acb-dd60a5166632.png)

**Comment by zeiphon** [comment]
> Can you post what errors are printed in the javascript console?
> 
> Maybe it's complaining it can't find `encKey`? Do you have `WASecretBundle` under the `LocalStorage`?

There don't seem to be any console errors, and my localStorage.WASecretBundle contains:
`"{"key":"nZxt****","encKey":"JcaEJ****","macKey":"nZxt****"}"`

**Comment by tomer8007** [comment]
In version 1.4.5 I had that bug too and after some looking I noticed it was because `WebSocketInterception.js` was loaded **after** WhatsApp's code, so the interception wasn't working.

So I made [this commit](https://github.com/tomer8007/whatsapp-web-incognito/commit/7fe2674160f684c26919aa2274636cec52550b56) which worked for me.

I'l try to see how can I reproduce this in 1.4.6 too.

**Comment by cardinal2019** [comment]
Hi Tomer,

Sorry but I dont know much about it. Can you teach how I put the script
please?
thanks a lot


Qualquer dúvida estamos a disposição!

*Richard Coelho*
Contador
CRC/SC 039470/O-6
(48) 3031-6600/3207-1592









*Confidencialidade:* A informação contida nesta mensagem de e-mail,
incluindo quaisquer anexos, é confidencial e está reservada apenas à pessoa
ou entidade para a qual foi endereçada. Se você não é o destinatário ou a
pessoa responsável por encaminhar esta mensagem ao destinatário, você está,
por meio desta, notificado que não deverá rever, retransmitir, imprimir,
copiar, usar ou distribuir esta mensagem de e-mail ou quaisquer anexos.
Caso você tenha recebido esta mensagem por engano, por favor, contate o
remetente imediatamente e apague esta mensagem de seu computador ou de
qualquer outro banco de dados. Muito obrigado.

*Confidentiality Notice:* The information contained in this e-mail message,
including any attachment, is confidential and is intended only for the
person or entity to which it is addressed. If you are neither the intended
recipient nor the employee or agent responsible for delivering this message
to the intended recipient, you are hereby notified that you may not review,
retransmit, convert to hard copy, copy, use or distribute this email
message or any attachments to it. If you have received this email in error,
please contact the sender immediately and delete this message from any
computer or other data bank, Thank you.




[image: Descrição: Descrição: Descrição: Descrição:
http://www.avon.com.pt/PRSuite/static/images/newsletter/images/print.jpg]






<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Livre
de vírus. www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>.
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

Em qua, 7 de ago de 2019 às 02:36, Tomer <notifications@github.com>
escreveu:

**Comment by tomer8007** [comment]
Is it working for anybody?

**Comment by cardinal2019** [comment]
good morning,

still no luck here! :(


Qualquer dúvida estamos a disposição!

*Richard Coelho*
Contador
CRC/SC 039470/O-6
(48) 3031-6600/3207-1592









*Confidencialidade:* A informação contida nesta mensagem de e-mail,
incluindo quaisquer anexos, é confidencial e está reservada apenas à pessoa
ou entidade para a qual foi endereçada. Se você não é o destinatário ou a
pessoa responsável por encaminhar esta mensagem ao destinatário, você está,
por meio desta, notificado que não deverá rever, retransmitir, imprimir,
copiar, usar ou distribuir esta mensagem de e-mail ou quaisquer anexos.
Caso você tenha recebido esta mensagem por engano, por favor, contate o
remetente imediatamente e apague esta mensagem de seu computador ou de
qualquer outro banco de dados. Muito obrigado.

*Confidentiality Notice:* The information contained in this e-mail message,
including any attachment, is confidential and is intended only for the
person or entity to which it is addressed. If you are neither the intended
recipient nor the employee or agent responsible for delivering this message
to the intended recipient, you are hereby notified that you may not review,
retransmit, convert to hard copy, copy, use or distribute this email
message or any attachments to it. If you have received this email in error,
please contact the sender immediately and delete this message from any
computer or other data bank, Thank you.




[image: Descrição: Descrição: Descrição: Descrição:
http://www.avon.com.pt/PRSuite/static/images/newsletter/images/print.jpg]






<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Livre
de vírus. www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>.
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

Em sex, 9 de ago de 2019 às 09:34, Tomer <notifications@github.com>
escreveu:

**Comment by tomer8007** [comment]
OK, until I fix this problem you can work around by Refreshing the page without caching (Ctrl + F5).
