### ISSUE TITLE
Groups in multi-device

### ISSUE THREAD

**Issue by 9Datenshi** [tomer8007/whatsapp-web-incognito#62]
As I mentioned in the comment _https://github.com/tomer8007/whatsapp-web-incognito/issues/46#issuecomment-950237946_ , the groups are not working as they should.

**Comment by BarAppTeam** [comment]
Hi, is there anything new on the issue? The bug still exists unfortunately @tomer8007

**Comment by tomer8007** [comment]
@BarAppTeam I'll try to fix the message restore feature, but I need a stable way to reproduce your other problem, becuase I don't have it right now.
