### ISSUE TITLE
Cannot see people's online status or Last Seen after 2.2142.12 update

### ISSUE THREAD

**Issue by noopdles** [tomer8007/whatsapp-web-incognito#64]
After updating to 2.2142.12, online and last seen information for contacts is no longer visible. The incognito and block last seen features however remain functional.

Please note that this behaviour starts occurring once you close and re-open the application after logging in for the first time - last seen statuses do show up on your first login (when linking through QR code).

**Comment by tomer8007** [comment]
This is an issue that I've seen occurring only in Multi-Device mode. It appears that for some reason subscribing for a contact's presence updates will not actually trigger a presence update from WhatsApp servers if you are not marked as available yourself.

This is why you have the following subtitle:

![image](https://user-images.githubusercontent.com/11458759/140531488-5666c1a0-6be5-4111-b881-b562442625d8.png)

**Comment by ritastar** [comment]
Hola , desde la última actualización no puedo ver a los contactos que están en línea, por favor traten de solucionar ese inconveniente con algún otro parche o actualización. GRACIAS!

**Comment by ritastar** [comment]
En atención a lo que escribió tomeer, deshabilite la opción Beta de que posibilita tener hasta 4 dispositivos sin mantener el teléfono conectado y se SOLUCIONÓ, el problema de de que no podía ver en linea a los contactos. GRACIAS por sus aportes!
