### ISSUE TITLE
Download status images and videos directly from site.

### ISSUE THREAD

**Issue by sunnag7** [tomer8007/whatsapp-web-incognito#68]
It will be a great feature wherein we can download status images and videos directly from site.

_Originally posted by @sunnag7 in https://github.com/tomer8007/whatsapp-web-incognito/discussions/67_

**Comment by sunnag7** [comment]
Any updates here?

**Comment by tomer8007** [comment]
@sunnag7 No, I'm not actively working on this now.

**Comment by tomer8007** [comment]
@sunnag7 I see this is a highly requested feature. Will try to see how hard it is to implement.

**Comment by IsaacHatton** [comment]
I did a bit of looking, if the status is a video
![image](https://github.com/tomer8007/whatsapp-web-incognito/assets/74068072/6c7d041f-3541-48af-bab5-b9401035b933)
If it's an image
![image](https://github.com/tomer8007/whatsapp-web-incognito/assets/74068072/c7740080-d786-4e51-9ee5-69983e76dd70)
If it's text, I don't really have any easy ideas, but downloading isn't particularly relevant here.

If you want I could have a go at implementing this, however it might take a while as my knowledge of this codebase is small.
