### ISSUE TITLE
Whatsapp Beta

### ISSUE THREAD

**Issue by UgurLuckSkyGok** [tomer8007/whatsapp-web-incognito#70]
After upgrading to whatsapp beta, it doesn't recover deleted messages. And "Mark as read" is not working correctly.

**Comment by tomer8007** [comment]
Both features are working for me, except message recovery for groups, which is #62. Do you have javascript errors maybe?

**Comment by MacgyverJohnson** [comment]
same here...in beta...read receipts are being sent automatically....

**Comment by tomer8007** [comment]
Working on it...
