### ISSUE TITLE
Could to do something similar but for whatsapp android?

### ISSUE THREAD

**Issue by pinnakkkk** [tomer8007/whatsapp-web-incognito#72]
The best thing about this mod/extension is that it's open source so no need to worry about data & privacy stuff. And I would love to have something similar to this on android as well.
P.S I'm aware of whatsapp apk mods but the data is sent thru pvt servers which makes it a little less trustworthy. :/

**Comment by tomer8007** [comment]
I don't plan to write something similar for Android. The closest I know is [WhatsApp Extensions xposed module](https://repo.xposed.info/module/com.suraj.waext), but this is probably not maintained anymore.
