### ISSUE TITLE
Contact's last seen status not displaying after forced multi-device mode Whatsapp web update 

### ISSUE THREAD

**Issue by gregmf90** [tomer8007/whatsapp-web-incognito#73]
Last seen isn't displaying anymore after the new whatsapp web update unless the phone version of whatsapp is also online. Is there an update planned to fix this?

**Comment by gregmf90** [comment]
I'm aware that this is a multi-device mode limitation, but considering that multi-device mode is now mandatory, is there a way around this?

**Comment by tomer8007** [comment]
@gregmf90 Can't you exit the beta program?

**Comment by gregmf90** [comment]
Unfortunately not. It doesn't have the option for that anymore

**Comment by gregmf90** [comment]
https://imgur.com/a/McbId43

**Comment by tomer8007** [comment]
I see. Unfortunately this might not be possible due to WhatsApp servers denying presence updates from users without presence updates themselves. Are you on beta?

**Comment by gregmf90** [comment]
That's disappointing... No this is the standard version 2.22.2.73

**Comment by tomer8007** [comment]
I'm on 2.22.2.73 and still have the option to exit beta. Will still try to do that anyway, though.

**Comment by gregmf90** [comment]
Thanks - that would be great if you could get this working despite multi-device mode.

Is there anything I can do to get out of beta? Apart from the the simple way which I don't have the option to do.

**Comment by tomer8007** [comment]
According to this website it appears that only some users are able to opt-out the multi-device beta.
https://wabetainfo.com/whatsapp-beta-for-android-2-21-23-10-whats-new/
I don't have many ideas except trying to re-install the app.
