### ISSUE TITLE
After upgrading then Mark as read not working 

### ISSUE THREAD

**Issue by onurhanerk** [tomer8007/whatsapp-web-incognito#74]
After upgrading to beta, it doesn't recover deleted messages. And "Mark as read" is not working correctly. I want the blue tick notification to never go away. But when you reply to the person, the message drops to a blue tick.

**Comment by tomer8007** [comment]
Blue notifications go away when you replay to a message, by design. The idea is that this way the conversation looks more natural. Also this is sometimes more convenient.
