### ISSUE TITLE
Messages not loading with error: "Waiting for this message. This may take a while"

### ISSUE THREAD

**Issue by chronos000** [tomer8007/whatsapp-web-incognito#76]
Every now and then (approximately once a week), all new messages stop showing on web.whatsapp.com. Instead, the text of these new messages show "Waiting for this message. This may take a while" . There is also a "[learn more](https://faq.whatsapp.com/general/security-and-privacy/seeing-waiting-for-this-message-this-may-take-a-while)" link, with possibly related information.

![image](https://user-images.githubusercontent.com/23492233/152079600-f84c2994-146b-4205-b1be-95c276668344.png)

I tried reloading web.whatsapp.com, but the problem persists. Even if I disable WAIncognito extension and reload the site, it still does not load new messages.

The only way I found to correct the problem is to completely logout from whatsappweb, and re-link the device once again.

I got into the multi-device program, and unfortunately I can't leave it to test if that has something to do with this.

Let me know if I can provide any logs or debug info.

**Comment by tomer8007** [comment]
I've seen such an issue in the past, but can't remember exactly what triggered it. I think this can happen if the extension messes up with incoming messages. I would try to
1. See if this is related to the message restore feature by trying to disable it
2. Look for javascript errors in the console

**Comment by chronos000** [comment]
> I've seen such an issue in the past, but can't remember exactly what triggered it. I think this can happen if the extension messes up with incoming messages. I would try to
> 
> 1. See if this is related to the message restore feature by trying to disable it

I forgot to mention that this was the first thing I tried. Disabling the restore feature and reloding the site did not solve the problem.

> 2. Look for javascript errors in the console

I'll do this next time the problem appears

Would something like this output be ok?
![image](https://user-images.githubusercontent.com/23492233/152249324-6ccdb035-6d6a-4b74-9b68-09dd535891c8.png)

Let me know if you would prefer any other way to export the data, or if you need any other information.

**Comment by tomer8007** [comment]
OK, looks like we have the problem. Will try to fix it next week.

**Comment by tizosa** [comment]
![image](https://user-images.githubusercontent.com/61971579/155891208-ea0e864a-c0a8-4cb5-8dd4-625b153a148b.png)

**Comment by tomer8007** [comment]
@tizosa @chronos000 Does it still happen for you since version 1.8.5?

**Comment by RezqZiyad** [comment]
> @tizosa @chronos000 Does it still happen for you since version 1.8.5?

No, it doesn't!

**Comment by tomer8007** [comment]
@RezqZiyad So it's a good thing, right?

**Comment by chronos000** [comment]
> @tizosa @chronos000 Does it still happen for you since version 1.8.5?

I have disabled multi-device in whatsapp because I didn't want to loose WAIncognito's habitlity to recovery deleted messages.

**Comment by tomer8007** [comment]
> the relevant logic is now disabled (https://github.com/tomer8007/whatsapp-web-incognito/commit/f9bceb9915c957634c2c88d020da4095606f8180).
Message restore feature is enabled again in v1.8.6.

**Comment by chronos000** [comment]
> > the relevant logic is now disabled ([f9bceb9](https://github.com/tomer8007/whatsapp-web-incognito/commit/f9bceb9915c957634c2c88d020da4095606f8180)).
> 
> Message restore feature is enabled again in v1.8.6 for multi-device.

The good news is that now deleted messages do not corrupt the database. The bad news is that instead of restoring the messages, now the deleted messages show "failed to restore message"

**Comment by tomer8007** [comment]
@chronos000 Uhh Is it happening also for messages that were deleted after you updated to 1.8.6?

**Comment by FieryRMS** [comment]
> @chronos000 Uhh Is it happening also for messages that were deleted after you updated to 1.8.6?

I am on 1.8.7, but the issue persists. Here is the error log,
![image](https://user-images.githubusercontent.com/43887302/163314408-15e5408e-9d54-4cc5-9526-bf078a17270c.png)

**Comment by chronos000** [comment]
> > @chronos000 Uhh Is it happening also for messages that were deleted after you updated to 1.8.6?
> 
> I am on 1.8.7, but the issue persists. Here is the error log, ![image](https://user-images.githubusercontent.com/43887302/163314408-15e5408e-9d54-4cc5-9526-bf078a17270c.png)
> 
> The message that was deleted was by me in a group chat which i deleted from the phone.

I am experiencing the same behaviour

**Comment by tomer8007** [comment]
@chronos000 @FieryRMS Still happening on 1.8.8?

**Comment by tomer8007** [comment]
@FieryRMS After the page finishes to load, is `SenderKeyMessage` defined? Also, do you still see the "Failed to restore message" for new messages?

**Comment by FieryRMS** [comment]
@tomer8007 Where do I check if it's defined? I sent the message from my phone after the page had loaded completely and even then the error was thrown.
No it doesn't show "Failed to restore message" anymore for deleted messages. It shows Whatsapp's "You deleted this message".

**Comment by FieryRMS** [comment]
@tomer8007 I did a search on your repo for definitions for `SenderKeyMessage` and it seems to defined in [core/parsing/.protobuf/WhisperTextProtocol.js](https://github.com/tomer8007/whatsapp-web-incognito/blob/master/core/parsing/.protobuf/WhisperTextProtocol.js#L71), this file seems to be missing on my end, perhaps this could be the reason?

![image](https://user-images.githubusercontent.com/43887302/164470273-fbaec061-ef57-425c-a15a-a050518bca98.png)
This location doesn't exist on my end,
![image](https://user-images.githubusercontent.com/43887302/164470403-176ec64a-8a61-48b6-9a3e-ad127de902ea.png)

**Comment by tomer8007** [comment]
Yes, this is the case here. I would guess this is because of the dot-folder `.proto`  that's being ignored by your computer somehow?

**Comment by tomer8007** [comment]
@FieryRMS Yes, this is apparently the case, and it's also an issue that I would probably never reproduce otherwise (so thank you). 
Please try version 1.8.9 (2fe930ba8d590910aaf38af30ea937f0ba54b040) from the store.

**Comment by FieryRMS** [comment]
@tomer8007 no problem!! And yes, now its working even from the store!
