### ISSUE TITLE
Mark as Read button disappeared, Deleted messages not being saved

### ISSUE THREAD

**Issue by FieryRMS** [tomer8007/whatsapp-web-incognito#82]
With the new update and multi-device support becoming official, some of the features of the extension stopped working. The mark as read button disappeared and deleted messages are no longer being saved.

I also noticed the "save deleted messages" option was removed from the menu, does this mean the feature is no longer supported?

**Comment by FieryRMS** [comment]
There is not much to see in the screenshot as its just completely gone.
![image](https://user-images.githubusercontent.com/43887302/162227300-59f7bcea-ce99-4bfb-88c6-ade2660c3665.png)

Glad to hear about the deleted messages option.

**Comment by tomer8007** [comment]
OK, I am aware that this happens in archived chats (#81). Is this by chance the case here?

**Comment by FieryRMS** [comment]
It happens with all chats, regardless of being archived or not, for both group and private chats. I am not sure what I did that caused it to happen, but it happened just after I updated WhatsappWeb.

**Comment by tomer8007** [comment]
1. Does the console look like this right after the problem happens?
2. If you refresh the page, does it change anything?

**Comment by FieryRMS** [comment]
I have gotten closer to figuring out the problem, I logged into whatsapp from incognito and the extension enabled and I got the mark as read button. Perhaps something from the previous version of whatsapp is messing with it? Is there a way to delete all data and cache from the site, but keep the deletedMsgs database?

1. The problem happens from the beginning, as soon as I load the page and enter an unread chat, there is no button to be seen. It doesnt "disappear", there was no button to begin with.
2. Yes. But this problem doesn't occur when I login from incognito.

**Comment by tomer8007** [comment]
Interesting finding, checking this now. 
1. I didn't mean the button, I was expecting to see `WhatsIncognito: --- Blocking RECEIPT action! ---` in the console log if it really did catch the receipt.

**Comment by FieryRMS** [comment]
Hi, me being the dumb person that I am, clicked the 🚫 button in the console application view, thinking it was clear filter button, and deleted the database anyways and read in horror that it was the "clear object store" button 😃. 

I cleared the "web.whatsapp.com" site data from "chrome://settings/content/all" and relogged into the site. It is now working as expected.

**Comment by tomer8007** [comment]
But - How did this happen? Were you logged in to the non-beta and it just started appearing after you entered multi-deive? Or maybe you were already in multi-device and updated the version?

**Comment by FieryRMS** [comment]
I was in the non-beta not so multi version. I got the notification of current version becoming unsupported and clicked on the update button. Perhaps this transition wasn't so smooth as I got a blank screen a few times, and had to close and reopen the site until I got to the login page. Logged in to the multi-device version and saw the button missing.
