### ISSUE TITLE
Option to hide the counter if marking messages as unread

### ISSUE THREAD

**Issue by elietannoury98** [tomer8007/whatsapp-web-incognito#84]
my use case is a little personal and not a general issue. The problem is that am using watusi 3 tweak on my phone so read receipts are never sent even if I send from my phone, so the messages counts never resets when I use whatsapp web (watusi clears the counter once I enter the chat) so is it possible that smthg similar could be done with your extension, example: let's say am chatting with someone and I received 240 messages from him without sending read receipts so the counter will keep showing 240 even if I close whatsappweb tab and open it the next day 240 will stay there, imagine the same thing with multiple chats that's a lot I think 😄, so maybe a clear counter without marking as read option would be great, thanks.

P.S: I had to use localStorage.clear(); in console to reset everything and that will force me to relink every time, any other more convenient workaround would be great

**Comment by tomer8007** [comment]
You can clear the unread counter without sending a read receipt by editing the chats DB, but I find this feature too specific so I don't want to implement this. At least not now where I have to make sure the main features are working.

**Comment by elietannoury98** [comment]
@tomer8007 okay is there a function that can be called from the console that can clear that? if not how can I access that DB to clear it? I really like the extension and that's my only issue so I don't mind clearing that db manually thanks

**Comment by tomer8007** [comment]
I believe this is under IndexedDB -> `model-stoarge` - > `chat`. In this table you're supposed to have an `unreadCount` variable for every chat.
