### ISSUE TITLE
Separate tab for deleted Messages

### ISSUE THREAD

**Issue by FieryRMS** [tomer8007/whatsapp-web-incognito#85]
Now that everything shifted to the multidevice mode, it is not possible to scroll past after a certain point in a chat. That means messages that were deleted before this point will become un-restorable since we are not physically able to goto that message and due to the way the extension works. I think now will be a good time than ever to implement a separate window for seeing the delete messages from a certain chat. This will prevent the part of the deleted database from becoming useless after a certain period and will give users an option  to see older messages that were deleted.

**Comment by tomer8007** [comment]
For now, if you really want to see older messages that were deleted, you can go to the DB manually inside IndexedDB.

**Comment by tomer8007** [comment]
But I find this feature not worth the invested time, so I won't do it.
