### ISSUE TITLE
Restored messages are in black text on black text bubble in dark mode

### ISSUE THREAD

**Issue by FieryRMS** [tomer8007/whatsapp-web-incognito#86]
When the messages are restored, the text is black, so is the message bubble in dark mode. This makes it almost impossible to see.
![image](https://user-images.githubusercontent.com/43887302/166183786-29bba7f0-1c5c-4b3c-81a2-e2b706a5813d.png)
![image](https://user-images.githubusercontent.com/43887302/166183806-f3555a64-2127-43d4-8dfc-794f633a4438.png)

**Comment by tomer8007** [comment]
This seems to be happening only when you change the theme after the message is loaded. If you refresh the page, it's in the correct color.

**Comment by FieryRMS** [comment]
I have always been using the dark mode, I noticed this a couple of times and reported it yesterday. I refreshed the page and it still happens.

**Comment by tomer8007** [comment]
Here is the code that's supposed to pick the right color:
https://github.com/tomer8007/whatsapp-web-incognito/blob/9b1f37dd00f8d2bc98422c8be2750f4dee9cc99d/core/ui.js#L501
You can put a breakpoint on this line and see what color it outputs when you load a deleted message. This is an unfortunate solution, but I can't debug a bug that I can't reproduce myself.

**Comment by FieryRMS** [comment]
it seems that ```localStorage["theme"]``` returns undefined for me, which is what is causing the issue. Running ```localStorage["theme"]="\"dark\""``` fixes the issue for me. Is this an issue caused by WhatsApp not setting the theme variable?
