### ISSUE TITLE
Actual version doesnt works on Firefox anymore

### ISSUE THREAD

**Issue by LcsPls** [tomer8007/whatsapp-web-incognito#89]
So... I tried to update it manually on firefox, but I have that message error:
![image](https://user-images.githubusercontent.com/89872304/167980272-d9a44f99-1cc2-4cd9-b332-7a00f6aeebb3.png)

it's something with "manifest v3 isnt suported by firefox" or something like that. :(

**Comment by LcsPls** [comment]
> As I said in #38, Firefox needs to add support for manifest v3.

oh I didnt knew, sorry
hope that will be soon

**Comment by gabrc52** [comment]
What about the syntax error in core/parsing/protobuf/WhisperTextProtocol.js ?
![image](https://user-images.githubusercontent.com/24363938/178163959-6b6dbaea-3a30-4726-8e7e-2fe2c71dc57c.png)

**Comment by aviv926** [comment]
> As I said in #38, Firefox needs to add support for manifest v3.

I tried now with firefox to upload the plugin but it seems there are still some problems. I think Firefox already supports V3, right?

![image](https://github.com/tomer8007/whatsapp-web-incognito/assets/51673860/217908e4-796d-4a0a-94d7-36b4715796a7)
