### ISSUE TITLE
`nodeParser.readNode` fails to `readAttributes` 

### ISSUE THREAD

**Issue by shenzhigang** [tomer8007/whatsapp-web-incognito#9]
Steps to reproduce the issue :
1. Installed the original WAIncognito extension in Chrome Web Store.
2. Login web.whatsapp.com.
3. Open DevTools in chrome.
4. Set **WAdebugMode = true**
5. Receive a message .
6. The element next to "message" is always **undefined**.
![c](https://user-images.githubusercontent.com/8005935/68756395-07b47b00-0645-11ea-948b-1f7d3fcf2e96.png)

Then I looked into this element from source code.

![a](https://user-images.githubusercontent.com/8005935/68754831-73e1af80-0642-11ea-9528-e29f00b94322.png)

Is it implied that the readNode is not work with the lastest version of whatsapp ?
Thanks.

**Comment by tomer8007** [comment]
Are you sure the attributes are not supposed to be `undefined` in this case? I can see that at least for some other types of payloads it contains some data :

![image](https://user-images.githubusercontent.com/11458759/68794348-86b2af00-0657-11ea-872d-383fe0f462fb.png)

**Comment by shenzhigang** [comment]
In some cases, it's not undefined. Thanks.
