### ISSUE TITLE
Messages are not being saved

### ISSUE THREAD

**Issue by FieryRMS** [tomer8007/whatsapp-web-incognito#90]
I am getting an error every time someone deletes a message, 
```[WhatsApp][3] -- Comms.handleStanza unrecognized stanza```
followed by a bunch of information about the message.
The deletion is blocked but the data is not saved into the database. Refreshing the page doesn't restore the message.
It is a direct chat if that information is important. I have yet to notice it in a group chat.

**Comment by tomer8007** [comment]
Thank you for the report. BTW the line `[WhatsApp][3] -- Comms.handleStanza unrecognized stanza` is normal intentional, it's printed because the WhatsApp client does not know how to handle our fake `blocked_node`.
