### ISSUE TITLE
Problemas con el bloqueo de confirmación de lectura

### ISSUE THREAD

**Issue by ritastar** [tomer8007/whatsapp-web-incognito#92]
Buenas equipo de githb, les cuento que la app esta muy inestable... a pesar que tengo marcada la opción de bloqueo de confirmación de lectura , cuando veo un estado de una persona  le sale como visto, lo mismo cuando entro al chat se marca como leido y eso es algo que no quiero que sucesas.  Si pueden solucionar ese fallo les agradecería. Tampoco esta funcionado la opcion de esta ocultar la conexión, a pesar que tengo marcada la opción que se oculte por momentos me ven en linea. Saludos y Gracias por el  trabajo que hacen

**Comment by tomer8007** [comment]
Hey, thanks for reaching out.
I'll need more data to help me reproduce this.
Do you see any javascript errors? Maybe you can make a video showing
the problem?

On 6/4/22, ritastar ***@***.***> wrote:
> Buenas equipo de githb, les cuento que la app esta muy inestable... a pesar
> que tengo marcada la opción de bloqueo de confirmación de lectura , cuando
> veo un estado de una persona  le sale como visto, lo mismo cuando entro al
> chat se marca como leido y eso es algo que no quiero que sucesas.  Si pueden
> solucionar ese fallo les agradecería. Tampoco esta funcionado la opcion de
> esta ocultar la conexión, a pesar que tengo marcada la opción que se oculte
> por momentos me ven en linea. Saludos y Gracias por el  trabajo que hacen

>

> --

> Reply to this email directly or view it on GitHub:

> https://github.com/tomer8007/whatsapp-web-incognito/issues/92

> You are receiving this because you are subscribed to this thread.

>

> Message ID: ***@***.***>


-- 
--------
Tomer

**Comment by tomer8007** [comment]
~~I'll need more data to help me reproduce this.
Do you see any javascript errors? Maybe you can make a video showing
the problem?~~
I think I identified the cause for this in bc9dd0f8ace36464463a1defc415987d66cbc5d4, please try version 1.9.4 and tell me if it's working.

**Comment by ritastar** [comment]
Tomer estoy con la versión 1.94 y hasta ahora parece funcionar bien. Si llegase a dar algún error te avisaré. Gracias por tu trabajo, eres una persona genial. Saludos
