### ISSUE TITLE
Block read receipts when sending a message

### ISSUE THREAD

**Issue by pablo-gbr** [tomer8007/whatsapp-web-incognito#95]
I noticed that when I send a message it will send the read receipt, looks like it's not happening when I send media (I sent a video and it said it's blocking the read receipt for that chat).
Is it possible to block with any type of message?

Thanks for your job!

**Comment by tomer8007** [comment]
Hi, read receipts are supposed to be sent for any kind of message when you replay to them, by design. The idea is that this way the conversation looks more natural and it's more convenient. Why would you want to keep blocking read receipts even after you replay to a message?

**Comment by NightWolf1038** [comment]
Since I know that a lot of WhatsApp mods that have this functionality, I thought this extension did that exact same thing and maybe have an option to enable read receipts after replying.

**Comment by tomer8007** [comment]
@pablo-gbr @krashish8 I added this as an opt-out feature in e202d0bb7deffc8a61f14ec8a9e22bfa696b7e32.
