### ISSUE TITLE
add an option for disabling the link preview

### ISSUE THREAD

**Issue by nsa** [tomer8007/whatsapp-web-incognito#98]
It would be nice if you implement an option for disabling the link previews

**Comment by tomer8007** [comment]
Why would anyone want to not see preview of messages with links?

**Comment by nsa** [comment]
because it is somewhat annoying and brings no usefulness. I got tired of clicking the "X" button everytime I want to send a link.
<img width="237" alt="image" src="https://user-images.githubusercontent.com/4787945/180602724-05cee403-c7db-497c-9174-edab97b5b76e.png">
<img width="1020" alt="image" src="https://user-images.githubusercontent.com/4787945/180602796-6b629dea-21f4-4bbb-ad36-674d47cc293a.png">

**Comment by tomer8007** [comment]
Oh, yes, this is one of the [still unsupported features of the multi-device web version](https://wabetainfo.com/whatsapp-is-enabling-link-previews-on-whatsapp-desktop/), but it should be added by WhatsApp soon.
